import sys
import re
import argparse

# Parse command line arguments
parser = argparse.ArgumentParser(description='Generate Plumed 2.8 configuration file for steered MD')
parser.add_argument('--equilibrate', type=str, help='Equilibrate template file for Plumed configuration')
parser.add_argument('--ini_com', type=str, help='Initialisation file for Plumed configuration')
parser.add_argument('--meta', type=str, help='Metadynamics template file for Plumed configuration')
parser.add_argument('--ndx', type=str, help='Index file generated by Charmm-GUI')
parser.add_argument('--output', type=str, help='Output directory for Plumed configuration')
parser.add_argument('--setup', type=str, help='Setup gro file for Plumed configuration')
parser.add_argument('--force', type=str, help='Force constant for pulling in kJ/(mol nm^2)', default=1000)
parser.add_argument('--speed', type=int, help='Pulling speed for pulling in nm/ns', default=2)
parser.add_argument('--name', type=str, help='Name to use for output data in PLUMED configuration')

args = parser.parse_args()

def main(args):
    print(f'Generating Plumed configuration file for steered MD with the following arguments: {args}')
    # Load template file
    with open(args.equilibrate, 'r') as f:
        equilibrate = f.read()

    with open(args.ini_com, 'r') as f:
        ini_com = f.read()

    with open(args.meta, 'r') as f:
        meta = f.read()

    # Load index file
    with open(args.ndx, 'r') as f:
        ndx = f.read()

    # Load setup gro file
    with open(args.setup, 'r') as f:
        gro = f.read()

    # Find the membrane atom numbers using the ndx file
    # This should be much easier than using the gro file
    # In the index file, the first block are the membrane atoms
    # So we take the first and last atom numbers from that block
    membrane_start = int(ndx.split('\n')[1].split()[0])
    membrane_end = 0
    for line in ndx.split('\n')[1:]:
        if line == '':
            break
        else:
            membrane_end = int(line.split()[-1])
    print(f'Membrane start: {membrane_start}')
    print(f'Membrane end: {membrane_end}')

    # Find the atom numbers for the ligand we want to do steered MD on
    # Easiest way to do this is probably using regex on the gro file
    # The gro file is formatted like this:
    # 7072LIG      O42774   3.567   3.601   8.056
    # We want to find the atom numbers for the LIG atoms, in this it's 42774
    atom_str = re.findall(r'\d+LIG\s+[A-Z]+\d+', gro)
    atom_num = [a[-5:] for a in atom_str]
    print(f'Atom strings: {atom_str}')
    print(f'Found atom numbers: {atom_num}')

    # Generate the Plumed configuration file for initialising the COM
    with open(args.output + 'ini_com.dat', 'w') as f:
        f.write(ini_com.format(lig=str(atom_num[0]) + '-' + str(atom_num[-1])))

    # Generate the Plumed configuration file for equilibrating the system
    with open(args.output + 'equilibrate.dat', 'w') as f:
        f.write(equilibrate.format(lig=str(atom_num[0]) + '-' + str(atom_num[-1])))

# If no arguments are provided, use our hardcoded values
# example: python generate_plumed.py --template smd_template.dat --output ../../basolateral/charmm-gui-2960967181-nacl-charmm36/gromacs/caffeine/smd_vfast.dat --setup ../../basolateral/charmm-gui-2960967181-nacl-charmm36/gromacs/caffeine/setup.gro --force 1000 --speed 4 --name vfast 
if len(sys.argv) == 1:
    membranes = ['../../apical/charmm-gui-2960669761-charmm36-nacl/gromacs/', '../../basolateral/charmm-gui-2960967181-nacl-charmm36/gromacs/']
    molecules = ['trihexyphenidyl', 'isopropanol', 'caffeine', 'morphine-6-glucuronide', 'sucrose']

    for membrane in membranes:
        for molecule in molecules:
            args.equilibrate = 'equilibrate_template.dat'
            args.ini_com = 'ini_com_template.dat'
            args.meta = 'metadynamics_template.dat'
            args.output = membrane + molecule + '/'
            args.setup = membrane + molecule + '/setup.gro'
            args.ndx = membrane + 'index.ndx'
            main(args)
else:
    main(args)
